export const UNSPLASH_ACCESS_KEY = process.env.NEXT_PUBLIC_UNSPLASH_ACCESS_KEY as string;
export const UNSPLASH_REDIRECT_URI = process.env.NEXT_PUBLIC_UNSPLASH_REDIRECT_URI as string;
export const UNSPLASH_SECRET_KEY = process.env.UNSPLASH_SECRET_KEY;
export const INFURA_IPFS_PROJECT_ID = process.env.INFURA_IPFS_PROJECT_ID;
export const INFURA_IPFS_PROJECT_SECRET = process.env.INFURA_IPFS_PROJECT_SECRET;
export const INFURA_API_KEY = process.env.NEXT_PUBLIC_INFURA_RINKEBY_PROJECT_ID;
